### PR TITLE
Implement feedback from maintainer for updating commits()

### PR DESCRIPTION
**Pull request by jdblischak**
@pcarbo I merged the upstream changes and then worked on the initial feedback from the maintainer:

- [x] Add argument `path` to `commits()` instead of `touching_commits()`
- [x] Document `path` and add example
- [x] Remove `inst/code`
- [x] Use 4 spaces for indenting C code
- [x] Use `/* */` for comments in C code
- [x] In `git2r_revwalk_list2`, add a check of the `path` argument and
open the repository with `git2r_repository_open`.
- [ ] Provide reproducible example for debugging

xref: https://github.com/ropensci/git2r/pull/372#issuecomment-455893081

### CODE REVIEW

**Comment by jdblischak** [comment]
When I ran `make check`, I got the following warning:

```
* checking whether package ‘git2r’ can be installed ... WARNING
Found the following significant warnings:
  git2r_revwalk.c:291:29: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const git_error *' [-Wint-conversion]
```

This error isn't present in the master branch of the upstream repo. However, I was able to install this version and run `git2r::commits()` without error.

**Comment by jdblischak** [comment]
Also, encouragingly, when I ran the simple example code, it executed without error. I'll work on creating some more interesting tests.

**Comment by jdblischak** [comment]
An update on that warning. That had been on my macOS. I got the same warning on my Ubuntu. Furthermore, the Travis builds of my fork also had that warning for [Ubuntu](
https://travis-ci.com/jdblischak/git2r/jobs/202318322#L237) and [macOS](https://travis-ci.com/jdblischak/git2r/jobs/202318319#L984). Any ideas?

**Comment by jdblischak** [comment]
I fixed the warning in a99d3c7.

**Comment by jdblischak** [comment]
The commits are being filtered correctly for the basic test. However, I can't figure out the order the commits are being returned. Would it be possible to update `git2r_revwalk_list2` to accept the arguments `topological`, `time`, and `reverse` like `git2r_revwalk_list` to ensure a consistent ordering of commits?

**Comment by jdblischak** [comment]
I added support for sorting the commits in 4bf000f.

**Comment by jdblischak** [comment]
@pcarbo This is ready for review.

Do you know the difference between `git_revwalk_push_head` and `git_revwalk_push`? The function you added uses the former, whereas `git2r_revwalk_list` uses the latter. I had to change one instance of `git_revwalk_push_head` to `git_revwalk_push` in order to support the argument `ref`, and I'm wondering if that could be a potential cause of the slight differences we are observing between the results when running the C function directly versus wrapped in git2r.

**Comment by pcarbo** [comment]
@jdblischak I will merge now and do some testing and review after.

**Comment by pcarbo** [comment]
> Do you know the difference between git_revwalk_push_head and git_revwalk_push?

@jdblischak We should be consistent with what they have. I suspect they do the same thing, but `git_revwalk_push` is more flexible. In any case, the difference still persists.

**Comment by jdblischak** [comment]
> In any case, the difference still persists.

Do you have a suspicion of what is causing the problem? If I recall correctly, we found a discrepancy in a repo with many commits. If you have an idea of what is creating the difference (e.g. merge commits, file renames, etc), I can try to produce the bug in the test file.

**Comment by pcarbo** [comment]
@jdblischak I'm working on understanding what is going on. In the meantime, I'm finding that the sorting by time doesn't work at all. Try this example from the [dsc](https://github.com/stephenslab/dsc) repository:

```R
library(git2r)
out <- commits(path = "dscrutils/R/dscquery.R",topological = TRUE,time = TRUE)
sapply(out,function(x) as.character(x$author$when))
```

This is what I get:

```
 [1] "2018-05-04 15:02:04" "2018-02-07 20:53:14" "2018-02-20 08:32:28"
 [4] "2018-02-07 23:56:25" "2018-02-07 23:29:40" "2019-02-08 09:37:14"
 [7] "2018-02-07 23:06:10" "2019-02-15 12:26:48" "2018-02-20 17:10:02"
[10] "2018-02-20 17:08:12" "2018-02-20 16:31:45" "2018-02-20 15:55:51"
[13] "2018-06-26 17:32:31" "2018-09-29 13:02:22" "2019-03-20 08:25:49"
[16] "2018-03-05 21:48:03" "2019-02-11 14:56:31" "2019-01-16 22:53:14"
[19] "2019-03-19 15:37:10" "2019-03-19 15:22:55" "2019-03-19 14:39:34"
[22] "2018-03-05 00:17:22" "2018-06-01 09:08:40" "2019-01-06 21:42:22"
[25] "2019-03-19 11:04:16" "2019-03-19 07:31:00" "2019-03-18 16:46:22"
[28] "2019-03-18 16:35:32" "2019-03-18 15:54:37" "2019-03-15 17:12:03"
[31] "2018-05-22 10:02:12" "2018-05-22 07:21:23" "2018-05-04 17:19:21"
[34] "2019-03-15 15:41:33" "2019-03-15 15:18:33" "2018-05-15 18:43:51"
[37] "2018-02-21 13:53:20" "2018-02-09 09:01:44" "2018-02-09 08:19:45"
[40] "2018-02-08 23:12:50" "2018-02-08 00:13:33"
```

**Comment by jdblischak** [comment]
> Do you get the same thing?

@pcarbo Yes, I get the same thing. However, it is unclear to me that `topological` or `time` are having an effect without the `path` argument. The results are the same whether these settings are `TRUE` or `FALSE`. It is just that without `path` set, they are already sorted.

```
library(git2r)

# path_time
path_time <- sapply(commits(path = "dscrutils/R/dscquery.R", topological = TRUE, time = TRUE),
                    function(x) as.character(x$author$when))

# path_notime
path_notime <- sapply(commits(path = "dscrutils/R/dscquery.R", topological = FALSE, time = FALSE),
                    function(x) as.character(x$author$when))
stopifnot(path_time == path_notime)

# nopath_time
nopath_time <- sapply(commits(topological = TRUE, time = TRUE),
                      function(x) as.character(x$author$when))

# nopath_notime
nopath_notime <- sapply(commits(topological = FALSE, time = FALSE),
                    function(x) as.character(x$author$when))
stopifnot(nopath_time == nopath_notime)

```

**Pull request merged**
